### PR TITLE
Parse Class/Interface 'extends' and 'implements' keywords

### PR DESCRIPTION
**Pull request by paduc**
I need to be able to parse the `extends` and `implements` keywords available in PlantUML (see [docs](https://plantuml.com/class-diagram#6e0d446ea2c5bf82)).

I discovered your parser just today, so please forgive me if the following proposal and PR don't respect this project's conventions. I'm glad to fix anything inappropriate.

This is what I did to achieve my goal:
- Created a new `class-extends-implements` test case
- Add `ExtendsImplements` expression in `plantuml.pegjs`
- Append `ExtendsImplements` to `Class` and `Interface` expressions
- Add `inherits` property to `Class` and `Interface` types
- In the `graph` formatter, if a `node` has an `inherits` value, add an `edge` just like the formatter would if the relationship was declared with `<|--`.

Cheers and thank you for your work on this !

### CODE REVIEW

**Comment by Enteee** [comment]
Hi @paduc and thank you for your pull request. I was not even aware that this syntax exists.

I just played around a bit with this and I found the things below. I would really like to see them implemented with this pull request as well. So tell me if you want to have a go, otherwise I'll probably make a few commits on my own :wink: 

### Multiple extends / implements

* [Classes can extend and implement multiple times](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuKhEIImkLd0iAagizCaiBb78p2t8ISrDpIifLW3nTS2a4PT3QbuAK3a0)
```
class ArrayList implements List, List2
```

**Conclusion**: We should probably represent this by storing all the extends and implements in an array of strings instead of just a single string. Also the default should be `[]`.

### Extending and implementing

* [Classes can extend and then implement](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuKhEIImkLd0iAagizCaiBb58hIX9pKifLW1pCdCBSb9pK_DA87mk1w0KK1C0)
```
class ArrayList extends List implements List
```

* [But classes can not implement and then extend](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuKhEIImkLd0iAagizCaiBb78p2t8ISrDpIifLW3pKojAKlDIe1mk1o0Rg0i0)
```
class ArrayList extends List implements List
```

### Enums can also extend/implement

* [I don't really know why, but this is also supported for enums](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuKhDAyrLS0KHgHKbgNafnGh-9HcfHM2HpDo2dDJSrBmI944k1w0Ye4O0)
```
enum Enum extends OtherEnum implements OtherEnum
```

**Conclusion**: I would split the extends and implements declarations into two different properties on the class/interface types.

**Comment by paduc** [comment]
Aha I knew my PR wasn't bullet proof ! Thanks for the remarks, I'll have a go at it.

**Comment by paduc** [comment]
Ok I pushed a new commit that 
- Adds multiple extends/implements
- Splits extends and implements to avoid wrong order
- Allow Enum to extend and implement

**Comment by Enteee** [comment]
@paduc I still have a few things that I would like to see changed, but I can do those myself. Would it be ok for you if i'd push a new commit on top of yours?

**Comment by paduc** [comment]
Sure my pleasure ! 
Do I need to do something on my side ?

**Comment by Enteee** [comment]
Nope, all good. Thanks. I think as upstream I can push automatically to your repo's branches for which you have a pull request open. But thank anyways @paduc . Give me a few minutes, working on it now.

**Comment by Enteee** [comment]
@paduc , done. Can you please review the pull request?

**Comment by paduc** [comment]
@Enteee perfect ! I approve ;)

**Pull request merged**
